Admin/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin.Models;

namespace Admin.Controllers
{
    public class RoomController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Room
        public ActionResult Index()
        {
            var roomModels = db.RoomModels.Include(r => r.applicationuser).Include(r => r.roonlist).Include(r => r.section).Include(r => r.subject);
            return View(roomModels.ToList());
        }

        // GET: Room/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomModel roomModel = db.RoomModels.Find(id);
            if (roomModel == null)
            {
                return HttpNotFound();
            }
            return View(roomModel);
        }

        // GET: Room/Create
        public ActionResult Create()
        {
            ViewBag.usersName = new SelectList(db.Users, "Id", "Firstname");
            ViewBag.roomName = new SelectList(db.RoomLists, "id", "Name");
            ViewBag.SectionDescription = new SelectList(db.SectionModels, "Id", "sectionName");
            ViewBag.SubjectName = new SelectList(db.SubjectModels, "Id", "SubjectName");
            return View();
        }

        // POST: Room/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,roomName,Description,yearlevel,SectionDescription,usersName,SubjectName")] RoomModel roomModel)
        {
            if (ModelState.IsValid)
            {
                db.RoomModels.Add(roomModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.usersName = new SelectList(db.Users, "Id", "Firstname", roomModel.usersName);
            ViewBag.roomName = new SelectList(db.RoomLists, "id", "Name", roomModel.roomName);
            ViewBag.SectionDescription = new SelectList(db.SectionModels, "Id", "sectionName", roomModel.SectionDescription);
            ViewBag.SubjectName = new SelectList(db.SubjectModels, "Id", "SubjectName", roomModel.SubjectName);
            return View(roomModel);
        }

        // GET: Room/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomModel roomModel = db.RoomModels.Find(id);
            if (roomModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.usersName = new SelectList(db.Users, "Id", "Firstname", roomModel.usersName);
            ViewBag.roomName = new SelectList(db.RoomLists, "id", "Name", roomModel.roomName);
            ViewBag.SectionDescription = new SelectList(db.SectionModels, "Id", "sectionName", roomModel.SectionDescription);
            ViewBag.SubjectName = new SelectList(db.SubjectModels, "Id", "SubjectName", roomModel.SubjectName);
            return View(roomModel);
        }

        // POST: Room/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,roomName,Description,yearlevel,SectionDescription,usersName,SubjectName")] RoomModel roomModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roomModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.usersName = new SelectList(db.Users, "Id", "Firstname", roomModel.usersName);
            ViewBag.roomName = new SelectList(db.RoomLists, "id", "Name", roomModel.roomName);
            ViewBag.SectionDescription = new SelectList(db.SectionModels, "Id", "sectionName", roomModel.SectionDescription);
            ViewBag.SubjectName = new SelectList(db.SubjectModels, "Id", "SubjectName", roomModel.SubjectName);
            return View(roomModel);
        }

        // GET: Room/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RoomModel roomModel = db.RoomModels.Find(id);
            if (roomModel == null)
            {
                return HttpNotFound();
            }
            return View(roomModel);
        }

        // POST: Room/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RoomModel roomModel = db.RoomModels.Find(id);
            db.RoomModels.Remove(roomModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin/Controllers/SectionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Admin.Models;

namespace Admin.Controllers
{
    public class SectionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Section
        public ActionResult Index()
        {
            return View(db.SectionModels.ToList());
        }

        // GET: Section/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SectionModel sectionModel = db.SectionModels.Find(id);
            if (sectionModel == null)
            {
                return HttpNotFound();
            }
            return View(sectionModel);
        }

        // GET: Section/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Section/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,sectionName,SectionDescription")] SectionModel sectionModel)
        {
            if (ModelState.IsValid)
            {
                db.SectionModels.Add(sectionModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sectionModel);
        }

        // GET: Section/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SectionModel sectionModel = db.SectionModels.Find(id);
            if (sectionModel == null)
            {
                return HttpNotFound();
            }
            return View(sectionModel);
        }

        // POST: Section/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,sectionName,SectionDescription")] SectionModel sectionModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sectionModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sectionModel);
        }

        // GET: Section/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SectionModel sectionModel = db.SectionModels.Find(id);
            if (sectionModel == null)
            {
                return HttpNotFound();
            }
            return View(sectionModel);
        }

        // POST: Section/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SectionModel sectionModel = db.SectionModels.Find(id);
            db.SectionModels.Remove(sectionModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin/Views/Shared/Success.cshtml
@model Admin.Models.RegisterViewModel
@{
    ViewBag.Title = "Success";
}

<div class="row">
    <h2>Info.</h2>
    @if (User.IsInRole("Administrator") || User.IsInRole("Agent"))
            {
        <p>The account is successfully added to the <a href="@Url.Action("Alllist", "Admin")">list of users</a>. </p>
    }
    else
    {
        <p>Your account is being reviewed by the Admin. </p>
        <p>You can <a href="@Url.Action("Login","Account")">log-in</a> after your account is activated using the activation link sent on your email. </p>
    }
</div>

Admin/Views/Shared/_Layout.cshtml
   <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title - Admin</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/Content/skins/_all-skins.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/ionicons.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/plugins/iCheck/square/blue.css">
    <link href="~/Content/jquery.modal.css" rel="stylesheet" />
    <link href="~/Content/admin-mod.css" rel="stylesheet" />
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="@Url.Action("Index","Home")" class="logo" style="background-image: linear-gradient(to right, #0F8F64,#2B7A77);">
                <span class="logo-mini" alt="Admin"><i class="fa fa-home"></i></span>
                <span class="logo-lg"><b>Admin</b> - Panel</span>
            </a>
            <nav class="navbar navbar-static-top">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        @if (User.Identity.IsAuthenticated)
						{
							<!-- Notifications -->
							<li class="dropdown notifications-menu">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<i class="fa fa-bell-o"></i>
									<span class="label label-warning"></span>
								</a>
								<ul class="dropdown-menu notification-dl">
									<li class="header notification-head"></li>
									<li>
										<ul class="menu">
											@*<li>
												<a href="#">
													<i class="fa fa-user text-aqua"></i><span class="label-desc"></span>
												</a>
											</li>*@
										</ul>
									</li>
									<li class="footer notification-foot"></li>
								</ul>
							</li>
							

		                    <li class="dropdown user user-menu row">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                   <img src="~/Content/images/user.png" class="user-image" alt="User Image">
                                   @User.Identity.Name
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="user-header">
                                        <img src="~/Content/images/user.png" class="img-circle" alt="User Image" />
                                        <p>
                                            @User.Identity.Name
                                            <small><b>Admin</b>Panel</small>
                                        </p>
                                    </li>
                                    <li class="user-footer">
                                        <div class="pull-left">
                                            <a href="@Url.Action("Index","Manage")" class="btn btn-default btn-flat">Profile</a>
                                        </div>
                                        <div class="pull-right">
                                            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                            {
                                                @Html.AntiForgeryToken()
                                                <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default btn-flat">Logout</a>
                                            }
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class="right-head-separator"></li>
                        }
                        else
                        {
                            <li class="dropdown user user-menu">
                                @Html.ActionLink("Log In","Login","Account", routeValues: null, htmlAttributes: new { id="loginlink"})
                            </li>
                        }
                    </ul>

                </div>
            </nav>
        </header>

        <aside class="main-sidebar" style="background-image: linear-gradient(to right, #012F2F,#2F5755);">
            <section class="sidebar">
                <div class="user-panel" style=" border-top: 4px solid #ff6a00;">
                    <div class="pull-left image">
                        <img src="~/Content/images/user.png" class="img-circle" alt="User image" />
                    </div>
                    <div class="pull-left info">
                        <p>@User.Identity.Name</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> online</a>
                    </div>
                </div>

                <ul class="sidebar-menu">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="sideMenu" data-label="mnuDashboard">
                        <a href="@Url.Action("Dashboard","Home")">
                            <i class="fa fa-bookmark"></i><span>Dashboard</span>
                        </a>
                    </li>
                    <li class="treeview sideMenu" data-label="Others">
                        <a href="#">
                            <i class="fa fa-tag"></i>
                            <span>Rooms, Subject and Section</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index","Room")"><i class="fa fa-asterisk"></i> Rooms</a></li>
                            <li><a href="@Url.Action("Index","Subjects")"><i class="fa fa-asterisk"></i> Subject</a></li>
                            <li><a href="@Url.Action("Index","Section")"><i class="fa fa-asterisk"></i> Section</a></li>
                        </ul>
                    </li>

                    <li class="treeview sideMenu" data-label="mnuTask">
                        <a href="#">
                            <i class="fa fa-tag"></i>
                            <span>Questionaire and Test</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index","Questionaires")"><i class="fa fa-asterisk"></i> Create Questionaire</a></li>
                            <li><a href="@Url.Action("Index","AnswerSheets")"><i class="fa fa-asterisk"></i> Answer Sheets</a></li>
                            <li><a href="@Url.Action("Index","tests")"><i class="fa fa-asterisk"></i> Test</a></li>
                        </ul>
                    </li>

                    <li class="treeview sideMenu" data-label="mnuquestionaire">
                        <a href="#">
                            <i class="fa fa-tag"></i>
                            <span>Student List</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li><a href="@Url.Action("Index","Students")"><i class="fa fa-asterisk"></i> Student</a></li>
                        </ul>
                    </li>

                    <li class="header">MANAGE</li>

                    <li class="treeview sideMenu" data-label="mnuUsers">
                        <a href="#">
                            <i class="fa fa-tag"></i>
                            <span>Manage Teachers</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            @if (User.IsInRole("Administrator"))
                            {
                                <li><a href="@Url.Action("Register","Account")"><i class="fa fa-asterisk"></i> New Teacher / User</a></li>
                                <li><a href="@Url.Action("Adminlist","Admin")"><i class="fa fa-asterisk"></i> Admin List</a></li>
                                <li><a href="@Url.Action("OtherList","Admin")"><i class="fa fa-asterisk"></i> Teachers List</a></li>
                                <li><a href="@Url.Action("AllList","Admin")"><i class="fa fa-asterisk"></i> All User List</a></li>
                                <li><a href="@Url.Action("ViewAllRoles","Admin")"><i class="fa fa-asterisk"></i> Role List</a></li>
                            }
                            else
                            {
                                <li><a href="@Url.Action("AgentList","Admin")"><i class="fa fa-asterisk"></i> Agent List</a></li>
                            }

                        </ul>
                    </li>

                    <li class="header">Quick Access</li>
                    <li><a href="@Url.Action("About","Home")"><i class="fa fa-circle-o text-aqua"></i> <span>Help</span></a></li>
                </ul>
                <br />
            </section>
        </aside>

        <div class="content-wrapper adminbody" style="min-height: 400px; background-image: linear-gradient(to right, #AF9071, #D1B79F);">
            <div class="mycontents">
                @RenderBody()
                <br />
            </div>
        </div>

        <footer class="main-footer" style="background-color: #878787;">
            <div class="pull-right hidden-xs">
                <b>Admin</b>Panel
            </div>
            <p><strong> @DateTime.Now.Year</strong> </p></> All rights reserved.
        </footer>
    </div>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/custom/app.min.js"></script>
    <script src="~/Scripts/custom/dashboard.js"></script>
    <script src="~/Scripts/custom/demo.js"></script>
	<script type="text/javascript">
		//Get record
		$(document).ready(function () {

		})

		function CheckRecord(agency) {
			$.ajax({
				type: 'GET',
				headers: {
					'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
				},
				url: '',
				contentType: "application/json",
				success: function (data) {
					if (data.length > 0) {
					}
				}
			});
		}

		if (localStorage) {
			//Menu
			var getActive = localStorage.getItem("ActiveMenu");
			if (getActive != null || getActive != "null") {
				$('.sideMenu').each(function () {
					if (getActive == $(this).attr('data-label')) {
						$(this).addClass('active');
					}
				});
			}
			//Sub menu
			var getActiveSub = localStorage.getItem("ActiveSubMenu");
			if (getActiveSub != null || getActiveSub != "null") {
				$('.submenu').each(function () {
					if (getActiveSub == $(this).attr('data-label')) {
						$(this).addClass('active');
						$('.submenu > ul').addClass('menu-open');
					}
				});
			}
			//Selecting menu
			$(document).on('click', '.sideMenu', function () {
				localStorage.setItem("ActiveMenu", $(this).attr('data-label'));
				if ($(this).attr('data-label') != "mnuPages") {
					localStorage.setItem("ActiveSubMenu", "null");
				}
			});
			//Selecting other submenu
			$(document).on('click', '.mnuPages > ul > li > a', function () {
				if ($('.submenu').hasClass('active')) {
					$('.submenu').trigger('click');
					localStorage.setItem("ActiveSubMenu", "null");
				}
			});
			//Selecting Sub menu
			$(document).on('click', '.submenu', function () {
				localStorage.setItem("ActiveSubMenu", $(this).attr('data-label'));
			});
		} else{
			alert("Sorry, your browser do not support local storage.");
		}
	</script>
</body>
</html>

Admin/Views/Shared/_Layout_locked.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title>@ViewBag.Title - INHS </title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/plugins/iCheck/square/blue.css">
</head>

<body class="locked-bg">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">INHS Online</a>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                 @Html.Partial("_LoginPartial")
            }
        </div>
       
    </div>

    <div class="container body-content">
        <div class="row mycontents">
            @RenderBody()
            @*<br />
            <hr class="footer-line" />
            <footer class="center-box footer-text">
                <p class="footer-tm">&copy; @DateTime.Now.Year - RFID</p>
            </footer>*@
        </div>
    </div>

   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Admin/Views/Shared/_Layout_normal.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title>@ViewBag.Title - INHS </title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/plugins/iCheck/square/blue.css">
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">INHS Online</a>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
                 @Html.Partial("_LoginPartial")
            }
        </div>
       
    </div>

    <div class="container-fluid body-content">
        <div class="row mycontents">
            @RenderBody()
            @*<br />
            <hr class="footer-line" />
            <footer class="center-box footer-text">
                <p class="footer-tm">&copy; @DateTime.Now.Year - RFID</p>
            </footer>*@
        </div>
    </div>

   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Admin/Views/Shared/_PartialUpload.cshtml
<form id="fileupload" method="POST" enctype="multipart/form-data" data-url="@Url.Action("Upload","FileUpload")" hidden>
    <div class="row fileupload-buttonbar">
        <div class="col-lg-7">
            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span>Add files...</span>
                <input type="file" name="files[]" multiple>
            </span>
            <button type="submit" class="btn btn-primary start" title="Start upload">
                <i class="glyphicon glyphicon-upload"></i>
                <span>Start upload</span>
            </button>
            <button type="reset" class="btn btn-warning cancel" title="Cancel upload">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel upload</span>
            </button>
            <button type="button" class="btn btn-danger delete" id="updelete" title="Delete">
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" class="toggle deletecheckbox" />
            <!-- The global file processing state -->
            <span class="fileupload-process"></span>
        </div>
        <!-- The global progress state -->
        <div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-success" style="width:0%;"></div>
            </div>
            <!-- The extended global progress state -->
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <!-- The global progress state -->
    <div class="col-lg-5 fileupload-progress fade">
        <!-- The global progress bar -->
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
        </div>
        <!-- The extended global progress state -->
        <div class="progress-extended">&nbsp;</div>
    </div>

    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
</form>
<br>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
            <button class="btn btn-primary start" disabled>
                <i class="glyphicon glyphicon-upload"></i>
                <span>Start</span>
            </button>
            {% } %}
            {% if (!i) { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <input type="checkbox" class="photocheckbox" id="photocheckbox-{%=i%}" data-pic="{%=file.name%}" data-picURL="{%=file.url%}" data-item="@ViewBag.id" />
        </td>
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
            <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
            <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}" {% if (file.deletewithcredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>